var teams = new Map
// Dictionary ((key)Betfair Team Name, (value)Iddaa Team Name)
//Turkish Super League
teams.set ('Trabzonspor', 'Trabzonspor')
teams.set ('Fenerbahce', 'Fenerbahçe')
teams.set ('Konyaspor', 'Konyaspor')
teams.set ('Basaksehir', 'Başakşehir')
teams.set ('Adana Demirspor', 'Adana Demirspor')
teams.set ('Alanyaspor', 'Alanyaspor')
teams.set ('Besiktas', 'Beşiktaş')
teams.set ('Antalyaspor', 'Antalyaspor')
teams.set ('Hatayspor', 'Hatayspor')
teams.set ('Fatih Karagumruk Istanbul', 'Fatih Karagümrük')
teams.set ('Kasimpasa', 'Kasımpaşa')
teams.set ('Galatasaray', 'Galatasaray')
teams.set ('Sivasspor', 'Sivasspor')
teams.set ('Kayserispor', 'Kayserispor')
teams.set ('Gaziantep FK', 'Gaziantep')
teams.set ('Giresunspor', 'Giresunspor')
teams.set ('Altay', 'Altay')
teams.set ('Rizespor', 'Rizespor')
teams.set ('Goztepe', 'Göztepe')
teams.set ('Malatyaspor', 'Yeni Malatyaspor')
//Turkish 1 Lig
teams.set ('Eyupspor', 'Eyüpspor')
teams.set ('Boluspor', 'Boluspor')
teams.set ('Genclerbirligi', 'Gençlerbirliği')
teams.set ('Bandirmaspor', 'Bandırmaspor')
teams.set ('Bursaspor', 'Bursaspor')
teams.set ('Denizlispor', 'Denizlispor')
teams.set ('Boluspor', 'Boluspor')
teams.set ('Umraniyespor', 'Ümraniyespor')
teams.set ('Keciorengucu', 'Keçiörengücü')
teams.set ('Menemen Belediyespor', 'Menemenspor')
teams.set ('Kocaelispor', 'Kocaelispor')
teams.set ('Manisa FK', 'Manisa Futbol Kulübü')
teams.set ('Istanbulspor', 'İstanbulspor')
teams.set ('Erzurum BB', 'Bşb Erzurum')
teams.set ('Tuzlaspor', 'Tuzlaspor')
teams.set ('Adanaspor', 'Adanaspor')
teams.set ('Samsunspor', 'Samsunspor')
teams.set ('Altinordu', 'Altınordu')
//English Premier League
teams.set ('Liverpool', 'Liverpool')
teams.set ('Man City', 'Manchester City')
teams.set ('Chelsea', 'Chelsea')
teams.set ('Tottenham', 'Tottenham')
teams.set ('Man Utd', 'Manchester United')
teams.set ('West Ham', 'West Ham')
teams.set ('Wolves', 'Wolverhampton')
teams.set ('Leicester', 'Leicester City')
teams.set ('Brighton', 'Brighton')
teams.set ('Brentford', 'Brentford')
teams.set ('Southampton', 'Southampton')
teams.set ('Crystal Palace', 'Crystal Palace')
teams.set ('Newcastle', 'Newcastle United')
teams.set ('Aston Villa', 'Aston Villa')
teams.set ('Leeds', 'Leeds United')
teams.set ('Everton', 'Everton')
teams.set ('Burnley', 'Burnley')
teams.set ('Watford', 'Watford')
teams.set ('Norwich', 'Norwich City')
teams.set ('Arsenal', 'Arsenal')
//English Championship
teams.set ('Fulham', 'Fulham')
teams.set ('Bournemouth', 'Bournemouth')
teams.set ('Huddersfield', 'Huddersfield')
teams.set ('Luton', 'Luton Town')
teams.set ('Nottm Forest', 'Nottingham Forest')
teams.set ('Sheff Utd', 'Sheffield United')
teams.set ('Millwall', 'Millwall')
teams.set ('Blackburn', 'Blackburn Rovers')
teams.set ('Middlesbrough', 'Middlesbrough')
teams.set ('QPR', 'QPR')
teams.set ('Coventry', 'Coventry')
teams.set ('West Brom', 'West Bromwich')
teams.set ('Swansea', 'Swansea City')
teams.set ('Stoke', 'Stoke City')
teams.set ('Preston', 'Preston')
teams.set ('Blackpool', 'Blackpool')
teams.set ('Cardiff', 'Cardiff City')
teams.set ('Bristol City', 'Bristol City')
teams.set ('Hull', 'Hull City')
teams.set ('Birmingham', 'Birmingham')
teams.set ('Reading', 'Reading')
teams.set ('Peterborough', 'Peterborough')
teams.set ('Derby', 'Derby County')
teams.set ('Barnsley', 'Barnsley')
//English League 1
teams.set ('Wigan', 'Wigan Athletic')
teams.set ('Rotherham', 'Rotherham')
teams.set ('MK Dons', 'MK Dons')
teams.set ('Sheff Wed', 'Sheffield Wednesday')
teams.set ('Plymouth', 'Plymouth')
teams.set ('Wycombe', 'Wycombe')
teams.set ('Sunderland', 'Sunderland')
teams.set ('Oxford Utd', 'Oxford')
teams.set ('Portsmouth', 'Portsmouth')
teams.set ('Bolton', 'Bolton')
teams.set ('Ipswich', 'Ipswich Town')
teams.set ('Cambridge Utd', 'Cambridge')
teams.set ('Charlton', 'Charlton')
teams.set ('Cheltenham', 'Cheltenham')
teams.set ('Accrington', 'Accrington')
teams.set ('Burton Albion', 'Burton Albion')
teams.set ('Shrewsbury', 'Shrewsbury')
teams.set ('Lincoln', 'Lincoln City')
teams.set ('Morecambe', 'Morecambe')
teams.set ('Gillingham', 'Gillingham')
teams.set ('Fleetwood Town', 'Fleetwood')
teams.set ('AFC Wimbledon', 'Wimbledon')
teams.set ('Doncaster', 'Doncaster')
teams.set ('Crewe', 'Crewe')
//English League 2
teams.set ('Exeter', 'Exeter City')
teams.set ('Colchester', 'Colchester')
teams.set ('Barrow', 'Barrow')
teams.set ('Forest Green', 'Forest Green')
teams.set ('Bradford', 'Bradford')
teams.set ('Tranmere', 'Tranmere')
teams.set ('Bristol Rovers', 'Bristol Rovers')
teams.set ('Salford City', 'Salford City')
teams.set ('Harrogate Town', 'Harrogate')
teams.set ('Swindon', 'Swindon Town')
teams.set ('Hartlepool', 'Hartlepool')
teams.set ('Port Vale', 'Port Vale')
teams.set ('Leyton Orient', 'Leyton Orient')
teams.set ('Scunthorpe', 'Scunthorpe')
teams.set ('Mansfield', 'Mansfield')
teams.set ('Sutton Utd', 'Sutton Utd')
teams.set ('Newport County', 'Newport')
teams.set ('Crawley Town', 'Crawley Town')
teams.set ('Oldham', 'Oldham')
teams.set ('Northampton', 'Northampton')
teams.set ('Stevenage', 'Stevenage')
teams.set ('Rochdale', 'Rochdale')
teams.set ('Walsall', 'Walsall')
teams.set ('Carlisle', 'Carlisle')
//English National League
teams.set ('Altrincham', 'Altrincham')
teams.set ('FC Halifax Town', 'Halifax Town')
teams.set ('Boreham Wood', 'Boreham Wood')
teams.set ('Dover', 'Dover')
teams.set ('Dag and Red', 'Dagenham&Red')
teams.set ('Barnet', 'Barnet')
teams.set ('Eastleigh', 'Eastleigh')
teams.set ('Bromley', 'Bromley')
teams.set ('Grimsby', 'Grimsby Town')
teams.set ('Stockport', 'Stockport')
teams.set ('Maidenhead', 'Maidenhead')
teams.set ('Weymouth', 'Weymouth')
teams.set ('Notts Co', 'Notts County')
teams.set ('Kings Lynn', 'Kings Lynn')
teams.set ('Southend', 'Southend')
teams.set ('Wealdstone', 'Wealdstone')
teams.set ('Woking', 'Woking')
teams.set ('Torquay', 'Torquay')
teams.set ('Wrexham', 'Wrexham')
teams.set ('Solihull Moors', 'Soli. Moors')
teams.set ('Yeovil', 'Yeovil Town')
teams.set ('Aldershot', 'Aldershot')
teams.set ('Chesterfield', 'Chesterfield')
//English National League South
teams.set ('Billericay Town', 'Billericay')
teams.set ('Bath City', 'Bath City FC')
teams.set ('Chelmsford', 'Chelmsford C')
teams.set ('Slough Town', 'Slough Town')
teams.set ('Chippenham', 'Chippenham')
teams.set ('Dulwich Hamlet', 'Dulwich')
teams.set ('Dartford', 'Dartford')
teams.set ('St Albans', 'Albans City')
teams.set ('Dorking Wanderers', 'Dorking Wand')
teams.set ('Concord Rangers', 'C Rangers')
teams.set ('Hampton and Richmond', 'Hampton&Rich')
teams.set ('Hungerford', 'Hungerford')
teams.set ('Hemel Hempstead', 'H Hempstead')
teams.set ('Maidstone Utd', 'Maidst. Utd')
teams.set ('Oxford City', 'Oxford City')
teams.set ('Braintree', 'Braintree')
teams.set ('Tonbridge Angels', 'Tonbridge')
teams.set ('Ebbsfleet Utd', 'Ebbsfleet')
teams.set ('Welling Utd', 'Welling Utd')
teams.set ('Havant and W', 'Hav&Waterloo')
//English National League North
teams.set ('Blyth Spartans', 'Blyth Spart')
teams.set ('Kidderminster', 'Kidd.minster')
teams.set ('Boston Utd', 'Boston Utd')
teams.set ('AFC Fylde', 'AFC Fylde')
teams.set ('Chester', 'Chester')
teams.set ('Farsley Celtic', 'Farsley Celt')
teams.set ('Chorley', 'Chorley')
teams.set ('Telford', 'Telford')
teams.set ('Darlington', 'Darlington')
teams.set ('Brackley Town', 'Brackley')
teams.set ('Guiseley', 'Guiseley')
teams.set ('Curzon Ashton', 'Curzon Ashto')
teams.set ('Hereford FC', 'Hereford')
teams.set ('Bradford PA', 'Bradford P A')
teams.set ('Kettering', 'Kettering')
teams.set ('Gateshead', 'Gateshead')
teams.set ('Leamington', 'Leamington')
teams.set ('Alfreton Town', 'Alfreton')
teams.set ('Southport', 'Southport')
teams.set ('Spennymoor Town', 'Spennymoor')
teams.set ('York City', 'York City')
teams.set ('Gloucester', 'Gloucester')
//German Bundesliga
teams.set ('Augsburg', 'Augsburg')
teams.set ('Hertha Berlin', 'Hertha Berlin')
teams.set ('Dortmund', 'B.Dortmund')
teams.set ('Wolfsburg', 'Wolfsburg')
teams.set ('Freiburg', 'Freiburg')
teams.set ('Bochum', 'Bochum')
teams.set ('Mainz', 'Mainz')
teams.set ('Stuttgart', 'Stuttgart')
teams.set ('Mgladbach', 'Monchengladbach')
teams.set ('FC Koln', 'Köln')
teams.set ('Arminia Bielefeld', 'Arminia Bielefeld')
teams.set ('Bayern Munich', 'Bayern Münih')
teams.set ('Hoffenheim', 'Hoffenheim')
teams.set ('Greuther Furth', 'Greuther Furth')
teams.set ('Union Berlin', 'Union Berlin')
teams.set ('Eintracht Frankfurt', 'Eintracht Frankfurt')
teams.set ('Leverkusen', 'B. Leverkusen')
teams.set ('RB Leipzig', 'Leipzig')
//German Bundesliga 2
teams.set ('Dynamo Dresden', 'Dynamo Dresden')
teams.set ('Holstein Kiel', 'Holstein Kiel')
teams.set ('Hannover', 'Hannover 96')
teams.set ('Fortuna Dusseldorf', 'F.Düsseldorf')
teams.set ('SV Sandhausen', 'Sandhausen')
teams.set ('St Pauli', 'Saint Pauli')
teams.set ('Hamburger SV', 'Hamburg')
teams.set ('Karlsruhe', 'Karlsruhe')
teams.set ('FC Heidenheim', 'Heidenheim')
teams.set ('Erzgebirge', 'Erzgebirge Aue')
teams.set ('Hansa Rostock', 'H. Rostock')
teams.set ('Jahn Regensburg', 'Jahn Regensburg')
teams.set ('Ingolstadt', 'Ingolstadt')
teams.set ('Paderborn', 'Paderborn')
teams.set ('SV Darmstadt', 'Darmstadt 98')
teams.set ('Schalke 04', 'Schalke 04')
teams.set ('Werder Bremen', 'Werder Bremen')
teams.set ('Nurnberg', 'Nürnberg')
//Almanya - 3. Lig
teams.set ('1860 Munich', '1860 Münih')
teams.set ('VFL Osnabruck', 'Osnabruck')
teams.set ('Wurzburger Kickers', 'Würzburg')
teams.set ('Viktoria Koln', 'Vik. Köln')
teams.set ('FSV Zwickau', 'Zwickau')
teams.set ('Wehen Wiesbaden', 'Wehen Wiesbaden')
teams.set ('Hallescher FC', 'Hallescher')
teams.set ('TSV Havelse', 'TSV Havelse')
teams.set ('SV Meppen', 'Meppen')
teams.set ('Dortmund II', 'Dortmund (A)')
teams.set ('Viktoria Berlin', 'FC Viktoria 1889 Berlin')
teams.set ('Duisburg', 'Duisburg')
teams.set ('Verl', 'SC Verl')
teams.set ('FC Magdeburg', 'Magdeburg')
teams.set ('Kaiserslautern', 'Kaiserslautern')
teams.set ('Saarbrucken', 'Saarbrucken')
teams.set ('Waldhof Mannheim', 'Mannheim 07')
teams.set ('Freiburg II', 'Freiburg II')
//German Regionalliga Northeast
teams.set ('Chemnitzer', 'Chemnitz')
teams.set ('Carl Zeiss Jena', 'Carl Zeiss Jena')
teams.set ('Hertha Berlin II', 'Hertha Berlin II')
teams.set ('Altglienicke', 'Altglienicke')
teams.set ('BFC Dynamo', 'Dynamo')
teams.set ('Tennis Borussia Berlin', 'Tennis Borussia Berlin')
teams.set ('Optik Rathenow', 'FSV Optik Rathenow')
teams.set ('VfB Auerbach', 'Auerbach')
teams.set ('Babelsberg', 'SV Babelsberg 03')
teams.set ('Cottbus', 'E. Cottbus')
teams.set ('Lichtenberg 47', 'Lichtenberg 47')
teams.set ('Lokomotiv Leipzig', 'Lok. Leipzig')
teams.set ('FSV 63 Luckenwalde', 'FSV 63 Luckenwalde')
teams.set ('Union Furstenwalde', 'Union Furstenwalde')
teams.set ('SV Tasmania Berlin', 'SV Tasmania Berlin')
teams.set ('FC Eilenburg', 'FC Eilenburg')
teams.set ('Chemie Leipzig', 'Chem Leipzig')
teams.set ('Berliner AK', 'Berliner AK')
//German Regionalliga West
teams.set ('Sportfreunde Lotte', 'Sportfreunde')
teams.set ('Rot-Weiss Essen', 'Weiss Essen')
teams.set ('Mgladbach II', 'Borussia M.Gladbach II')
teams.set ('SV 19 Straelen', 'SV 19 Straelen')
teams.set ('FC Koln II', 'Köln II')
teams.set ('Fortuna Koln', 'Fortuna Köln')
teams.set ('FC Wegberg-Beeck', 'Wegberg')
teams.set ('Rot-Weiss Ahlen', 'Rot Weis Ahl')
teams.set ('Bonner SC', 'Bonner')
teams.set ('SV Rodinghausen', 'Rodinghausen')
teams.set ('Uerdingen', 'Uerdingen 05')
teams.set ('VfB Homberg', 'VfB Homberg')
teams.set ('Rot-Weiss Oberhausen', 'Oberhausen')
teams.set ('Preussen Munster', 'Preussen 06 Munster')
teams.set ('Alemannia Aachen', 'A. Aachen')
teams.set ('Wuppertaler', 'Wuppertaler')
teams.set ('SV Lippstadt', 'Lippstadt 08')
teams.set ('Schalke 04 II', 'Schalke 04 II')
//German Regionalliga Bavaria
teams.set ('Augsburg II', 'Augsburg II')
teams.set ('Illertissen', 'Illertissen')
teams.set ('Greuther Furth II', 'Greuther Furth II')
teams.set ('TSV Rain/Lech', 'Rain Lech')
teams.set ('Bayern Munich II', 'Bayern Münih II')
teams.set ('Schweinfurt', 'Schweinfurt')
teams.set ('Schalding-Heining', 'Schalding')
teams.set ('Nurnberg II', 'Nürnberg (A)')
teams.set ('Heimstetten', 'Heimstetten')
//German Regionalliga Southwest
teams.set ('SG Sonnenhof', 'Grossaspach')
teams.set ('Elversberg', 'Elversberg')
teams.set ('Aalen', '1921 Aalen')
teams.set ('Rot-Weiss Koblenz', 'Rot-Weiss Ko')
teams.set ('Bahlinger SC', 'Bahlinger')
teams.set ('Hessen Kassel', 'Hessen Kassel')
teams.set ('SV Steinbach', 'Steinb. 1921')
teams.set ('Kickers Offenbach', 'Offenbacher')
teams.set ('Stuttgart II', 'Stuttgart II')
teams.set ('Homburg', 'Homburg-Saar')
//Spanish La Liga
teams.set ('Real Sociedad', 'Real Sociedad')
teams.set ('Betis', 'R.Betis')
teams.set ('Elche', 'Elche')
teams.set ('Mallorca', 'Mallorca')
teams.set ('Alaves', 'Alaves')
teams.set ('Rayo Vallecano', 'Vallecano')
teams.set ('Valencia', 'Valencia')
teams.set ('Osasuna', 'Osasuna')
teams.set ('Getafe', 'Getafe')
teams.set ('Villarreal', 'Villarreal')
teams.set ('Granada', 'Granada')
teams.set ('Levante', 'Levante')
teams.set ('Atletico Madrid', 'A.Madrid')
teams.set ('Espanyol', 'Espanyol')
teams.set ('Athletic Bilbao', 'A.Bilbao')
teams.set ('Celta Vigo', 'C.Vigo')
teams.set ('Sevilla', 'Sevilla')
teams.set ('Real Madrid', 'R.Madrid')
teams.set ('Barcelona', 'Barcelona')
teams.set ('Cadiz', 'Cadiz')
//Spanish Segunda Division
teams.set ('Eibar', 'Eibar')
teams.set ('Las Palmas', 'Las Palmas')
teams.set ('Amorebieta', 'Amorebieta')
teams.set ('Mirandes', 'Mirandes')
teams.set ('Leganes', 'Leganes')
teams.set ('Malaga', 'Malaga CF')
teams.set ('Valladolid', 'Real Valladolid')
teams.set ('Almeria', 'Almeria')
teams.set ('Sporting Gijon', 'S.Gijon')
teams.set ('Oviedo', 'Real Oviedo')
teams.set ('FC Cartagena', 'Cartagena')
teams.set ('Alcorcon', 'Alcorcon')
teams.set ('Ponferradina', 'SD Ponferradina')
teams.set ('Lugo', 'Lugo')
teams.set ('Burgos', 'CF Burgos')
teams.set ('Ibiza Eivissa', 'I. Eivissa')
teams.set ('Huesca', 'Huesca')
teams.set ('Zaragoza', 'Zaragoza')
teams.set ('Tenerife', 'Tenerife')
teams.set ('Fuenlabrada', 'Fuenlabrada')
teams.set ('Girona', 'Girona')
teams.set ('Sociedad B', 'Real Sociedad B')
//Spanish Primera Division RFEF Group 1
teams.set ('Celta Vigo B', 'Celta Vigo B')
teams.set ('CD Calahorra', 'CD Calahorra')
teams.set ('UD Logrones', 'Logrones')
teams.set ('Racing de Ferrol', 'Racing Club De Ferrol')
teams.set ('CF Rayo Majadahonda', 'Rayo Majadah')
teams.set ('Racing Santander', 'Santander')
teams.set ('Zamora', 'Zamora CF')
teams.set ('Tudelano', 'CD Tudelano')
teams.set ('Athletic Bilbao B', 'Athletic Bilbao B')
teams.set ('SD Logrones', 'SD Logrones')
teams.set ('CF Internacional Madrid', 'Sadcf Internacional De Ma')
teams.set ('SS Reyes', 'UD San Sebastian Reyes')
teams.set ('Talavera CF', 'Talavera R')
teams.set ('Deportivo', 'Deportivo')
teams.set ('Union de Salamanca', 'Real Union De Irun')
teams.set ('Valladolid B', 'Real Valladolid B')
teams.set ('Leonesa', 'Cultural Leonesa')
//Spanish Primera Division RFEF Group 2
teams.set ('Cornella', 'UE Cornella')
teams.set ('Villarreal B', 'Villarreal B')
teams.set ('UE Llagostera', 'UE Costa Brava')
teams.set ('Alcoyano', 'CD Alcoyano')
teams.set ('Linares Deportivo', 'Linares Deportivo')
teams.set ('CD Castellon', 'Castellon')
teams.set ('Barcelona B', 'Barcelona B')
teams.set ('Atletico Sanluqueno CF', 'A.Sanluqueno')
teams.set ('Algeciras', 'Algeciras CF')
teams.set ('UCAM Murcia', 'Ucam Murcia')
teams.set ('Atletico Baleares', 'CD Atletico Baleares')
teams.set ('Real Madrid Castilla', 'Real Madrid Castilla')
teams.set ('Sevilla B', 'Sevilla Atl.')
teams.set ('Betis B', 'Betis Deportivo Balompie')
teams.set ('Albacete', 'Albacete')
teams.set ('Linense', 'RB Linense')
teams.set ('Andorra CF', 'FC Andorra')
teams.set ('Sabadell', 'CE Sabadell FC')
//Spanish Segunda Division B - Group 1
teams.set ('CD Leganes II', 'CD Leganes B')
teams.set ('CDA Navalcarnero', 'Navalcarnero')
teams.set ('CD Cristo Atletico', 'CD Cristo Atletico')
teams.set ('U.D Llanera', 'UD Llanera')
teams.set ('CD Mostoles', 'CD Mostoles Urjc')
teams.set ('Real Aviles', 'Real Aviles CF')
teams.set ('SD Compostela', 'Compostela')
teams.set ('Arosa FC', 'Arosa SC')
teams.set ('Bergantinos CF', 'Bergantinos CF')
teams.set ('AD Union Adarve', 'AD Union Adarve')
teams.set ('Marino Luanco', 'Club Marino De Luanco')
teams.set ('Gimnastica Segoviana CF', 'Gimnastica Segoviana CF')
teams.set ('Pontevedra CF', 'Pontevedra')
teams.set ('UP Langreo', 'UP Langreo')
teams.set ('Salmantino', 'Salamanca CF')
teams.set ('Union Club Ceares', 'UC Ceares')
teams.set ('Arenteiro', 'CD Arenteiro')
teams.set ('Coruxo', 'FC Coruxo')
//Spanish Segunda Division B - Group 2
teams.set ('UD Mutilvera', 'UD Mutilvera')
teams.set ('SD Rayo Cantabria', 'Rayo Cantabria')
teams.set ('AD San Juan', 'AD San Juan')
teams.set ('CD Burgos Promesas', 'Burgos CF Promesas')
teams.set ('CD Laredo', 'CD Laredo')
teams.set ('CD Ardoi', 'CD Ardoi FE')
teams.set ('Naxara CD', 'Naxara CD')
teams.set ('Arenas Club de Getxo', 'Arenas Club De Getxo')
teams.set ('SD Gernika Club', 'SD Gernika Club')
teams.set ('CA Osasuna II', 'Osasuna B')
teams.set ('CD Tropezon', 'CD Tropezon')
teams.set ('Pena Sport', 'Pena Sport')
teams.set ('UD Logrones II', 'UD Logrones B')
teams.set ('Sestao River', 'Sestao River Club')
teams.set ('CD Izarra', 'CD Izarra')
teams.set ('CD Cayon', 'CD Cayon')
teams.set ('Real Sociedad III', 'Real Sociedad C')
teams.set ('Racing Rioja CF', 'Racing Rioja CF')
//Spanish Segunda Division B - Group 3
teams.set ('Numancia', 'Numancia')
teams.set ('CA Tarazona', 'SD Tarazona')
teams.set ('Badalona', 'CF Badalona')
teams.set ('CE Andratx', 'CE Andratx')
teams.set ('Huesca B', 'SD Huesca B')
teams.set ('CD Ebro', 'CD Ebro')
teams.set ('Prat', 'AE Prat')
teams.set ('CD Ibiza Islas Pitiusas', 'CD Ibiza Islas Pitiusas')
teams.set ('Santa Eulalia', 'SCR Pena Deportiva')
teams.set ('Espanyol B', 'Espanyol II')
teams.set ('CD Brea', 'CD Brea')
teams.set ('CD Teruel', 'CD Teruel')
teams.set ('SD Ejea', 'SD Ejea')
teams.set ('Lleida', 'Club Lleida Esportiu')
teams.set ('Terrassa', 'Terrassa FC')
teams.set ('Cerdanyola del Valles', 'FC Cerdanyola Del Valles')
//Spanish Segunda Division B - Group 4
teams.set ('Antequera CF', 'Antequera CF')
teams.set ('AD Ceuta FC', 'AD Ceuta')
teams.set ('Cordoba', 'Cordoba')
teams.set ('UD Las Palmas II', 'UD Las Palmas Atletico')
teams.set ('Don Benito', 'Don Benito')
teams.set ('CD Coria', 'CD Coria')
teams.set ('San Roque Lepe', 'CD San Roque')
teams.set ('CF Panaderia Pulido', 'CF Panaderia Pulido')
teams.set ('UD Montijo', 'UD Montijo')
teams.set ('Villanovense', 'Villanovense')
teams.set ('UD Tamaraceite', 'UD Tamaraceite')
teams.set ('Cadiz B', 'Cadiz B')
teams.set ('UD San Fernando', 'UD San Fernando')
teams.set ('Xerez', 'Xerez Deportivo FC')
teams.set ('Cacereno', 'CP Cacereno Sad')
teams.set ('Merida AD', 'Merida AD')
//Spanish Segunda Division B - Group 5
teams.set ('Intercity Sant Joan C.F', 'CF Intercity')
teams.set ('CA Pulpileno', 'Atletico Pulpileno')
teams.set ('Granada B', 'Granada B')
teams.set ('Atletico Levante UD', 'Atletico Levante UD')
teams.set ('Mar Menor CF', 'Mar Menor Club de Futbol')
teams.set ('UD Socuellamos', 'UD Socuellamos CF')
teams.set ('Aguilas', 'CDA Aguilas FC')
teams.set ('Hercules', 'Hercules CF')
teams.set ('CD Marchamalo', 'Marchamalo CD')
teams.set ('CD El Ejido 2012', 'El Ejid 2012')
teams.set ('CD Puertollano', 'Calvo Sotelo Puertollano')
teams.set ('UD Alzira', 'Alzira')
teams.set ('CD Toledo', 'CD Toledo')
teams.set ('La Nucia', 'CF La Nucia')
teams.set ('Atletico Mancha Real', 'ATL Mancha Real')
teams.set ('Eldense', 'Club Deportivo Eldense')
//French Ligue 1
teams.set ('Paris St-G', 'Paris Saint Germain')
teams.set ('Lens', 'RC Lens')
teams.set ('Reims', 'Reims')
teams.set ('Marseille', 'Marsilya')
teams.set ('Lille', 'Lille')
teams.set ('Strasbourg', 'Strasbourg')
teams.set ('Lyon', 'Lyon')
teams.set ('Montpellier', 'Montpellier')
teams.set ('Rennes', 'Rennes')
teams.set ('Lorient', 'Lorient')
teams.set ('Nice', 'Nice')
teams.set ('ESTAC Troyes', 'Troyes')
teams.set ('Nantes', 'Nantes')
teams.set ('Bordeaux', 'Bordeaux')
teams.set ('St Etienne', 'St Etienne')
teams.set ('Monaco', 'Monaco')
teams.set ('Clermont', 'Clermont Foo')
teams.set ('Angers', 'Angers')
teams.set ('Metz', 'Metz')
teams.set ('Brest', 'Brest')
//French Ligue 2
teams.set ('Caen', 'Caen')
teams.set ('Auxerre', 'AJ Auxerre')
teams.set ('Le Havre', 'Le Havre')
teams.set ('Grenoble', 'Grenoble')
teams.set ('Dijon', 'Dijon')
teams.set ('Guingamp', 'Guingamp')
teams.set ('Dunkerque', 'Dunkerque')
teams.set ('Amiens', 'Amiens')
teams.set ('Valenciennes', 'Valenciennes')
teams.set ('AC Ajaccio', 'Ajaccio')
teams.set ('Pau', 'Pau')
teams.set ('Sochaux', 'Sochaux')
teams.set ('Nimes', 'Nimes')
teams.set ('Rodez', 'Rod. Aveyro')
teams.set ('Nancy', 'AS Nancy')
teams.set ('Quevilly Rouen', 'US Quevillaise-Rouen Metr')
teams.set ('Bastia', 'SC Bastia')
teams.set ('Paris FC', 'Paris')
teams.set ('Toulouse', 'Toulouse')
teams.set ('Niort', 'Cham. Niort')
//French National
teams.set ('Le Mans', 'Le Mans')
teams.set ('FC Bastia-Borgo', 'FC Bastia Borgo')
teams.set ('Bourg-en-Bresse', 'FC Bourg-En-bresse Peronn')
teams.set ('Red Star', 'Red Star FC')
teams.set ('Sete', 'FC Sete 34')
teams.set ('Orleans', 'Orleans')
teams.set ('Avranches', 'US Avranches')
teams.set ('Cholet SO', 'Ol Choletais')
teams.set ('Creteil', 'US Creteil')
teams.set ('Villefranche Beaujolais', 'FC Villefranche-Beaujolai')
teams.set ('Chateauroux', 'Chateauroux')
teams.set ('Annecy', 'Annecy FC')
teams.set ('Stade Briochin', 'Saint Brieuc')
teams.set ('Concarneau', 'US Concarneau')
teams.set ('Sedan', 'Sedan-Ardennes')
teams.set ('Chambly Oise', 'Chambly Oise')
teams.set ('Laval', 'Stade Laval')
teams.set ('Boulogne', 'US Boulogne')
//Scottish Premiership
teams.set ('Motherwell', 'Motherwell')
teams.set ('Rangers', 'Rangers')
teams.set ('Ross Co', 'Ross County')
teams.set ('Celtic', 'Celtic')
teams.set ('Dundee', 'Dundee')
teams.set ('St Johnstone', 'St Johnstone')
teams.set ('Dundee Utd', 'Dundee Utd')
teams.set ('Hearts', 'Hearts')
teams.set ('St Mirren', 'St Mirren')
teams.set ('Hibernian', 'Hibernian')
teams.set ('Aberdeen', 'Aberdeen')
teams.set ('Livingston', 'Livingston')
//Scottish League One
teams.set ('Clyde', 'Clyde Bank')
teams.set ('Airdrieonians', 'Airdrieonian')
teams.set ('Cove Rangers', 'Cove Rangers')
teams.set ('Dumbarton', 'Dumbarton')
teams.set ('Falkirk', 'Falkirk')
teams.set ('Alloa', 'Alloa')
teams.set ('Peterhead', 'Peterhead')
teams.set ('East Fife', 'East Fife')
teams.set ('Montrose', 'Montrose')
teams.set ('Queens Park', 'Queen\'s Park')
//Scottish League Two
teams.set ('Stenhousemuir', 'Stenhousemur')
teams.set ('Stranraer', 'Stranraer')
teams.set ('Edinburgh City', 'Edinburgh')
teams.set ('Annan', 'Annan Athl.')
teams.set ('Kelty Hearts', 'Kelty Hearts FC')
teams.set ('Forfar', 'Forfar')
teams.set ('Albion', 'Albion Rov.')
teams.set ('Stirling', 'Stirling Alb')
teams.set ('Elgin', 'Elgin City')
teams.set ('Cowdenbeath', 'Cowdenbeath')
//Scottish Championship
teams.set ('Queen of South', 'Queen Of S.')
teams.set ('Ayr', 'Ayr United')
teams.set ('Kilmarnock', 'Kilmarnock')
teams.set ('Arbroath', 'Arbroath')
teams.set ('Partick', 'P. Thistle')
teams.set ('Dunfermline', 'Dunfermline')
teams.set ('Morton', 'G. Morton')
teams.set ('Inverness CT', 'Inverness')
teams.set ('Hamilton', 'Hamilton')
teams.set ('Raith', 'Raith Rovers')
//Irish Premier Division
teams.set ('Bohemians', 'Bohemians')
teams.set ('Shamrock Rovers', 'Shamrock R')
teams.set ('Derry City', 'Derry City')
teams.set ('UCD', 'Col. Dublin')
teams.set ('St Patricks', 'St. Patricks')
teams.set ('Finn Harps', 'Finn Harps')
teams.set ('Dundalk', 'Dundalk')
teams.set ('Shelbourne', 'Shelbourne')
teams.set ('Sligo Rovers', 'Sligo Rovers')
teams.set ('Drogheda', 'Drogheda')
//Irish Division 1
teams.set ('Wexford F.C', 'Wexford')
teams.set ('Waterford', 'Waterford')
teams.set ('Cork City', 'Cork City FC')
teams.set ('Cobh Ramblers', 'Cobh Rambler')
teams.set ('Galway Utd', 'Galway U')
teams.set ('Bray Wanderers', 'Bray Wand')
teams.set ('Longford', 'Longford')
teams.set ('Treaty United', 'Treaty United')
//Italian Serie A
teams.set ('Empoli', 'Empoli')
teams.set ('Napoli', 'Napoli')
teams.set ('Salernitana', 'Salernitana')
teams.set ('Fiorentina', 'Fiorentina')
teams.set ('Inter', 'Inter')
teams.set ('Roma', 'AS Roma')
teams.set ('Venezia', 'Venezia')
teams.set ('Atalanta', 'Atalanta')
teams.set ('Torino', 'Torino')
teams.set ('Spezia', 'Spezia')
teams.set ('Sassuolo', 'Sassuolo')
teams.set ('Juventus', 'Juventus')
teams.set ('Lazio', 'Lazio')
teams.set ('AC Milan', 'AC Milan')
teams.set ('Verona', 'Hellas Verona')
teams.set ('Sampdoria', 'Sampdoria')
teams.set ('Udinese', 'Udinese')
teams.set ('Genoa', 'Genoa')
teams.set ('Cagliari', 'Cagliari')
teams.set ('Bologna', 'Bologna')
//Italian Serie B
teams.set ('Ascoli', 'Ascoli')
teams.set ('Cittadella', 'Cittadella')
teams.set ('Cosenza', 'Cosenza')
teams.set ('Pordenone', 'Pordenone Calcio')
teams.set ('Crotone', 'Crotone')
teams.set ('US Cremonese', 'Cremonese')
teams.set ('Lecce', 'Lecce')
teams.set ('Pisa', 'AC Pisa')
teams.set ('Alessandria', 'US Alessandria Calcio 191')
teams.set ('Reggina', 'Urbs Reggina 1914')
teams.set ('Frosinone', 'Frosinone')
teams.set ('AC Monza', 'SS Monza 1912')
teams.set ('Benevento', 'Benevento')
teams.set ('Ternana', 'Ternana Calcio')
teams.set ('Brescia', 'Brescia')
teams.set ('Spal', 'SPAL')
teams.set ('Como', 'Como 1907')
teams.set ('LR Vicenza Virtus', 'LR Vicenza Virtus')
teams.set ('Perugia', 'Perugia')
teams.set ('Parma', 'Parma')
//Italian Serie C
teams.set ('Olbia', 'Olbia Calcio 1905')
teams.set ('Grosseto', 'US Grosseto')
teams.set ('ASD Aquila 1902', 'Aquila Montevarchi')
teams.set ('Gubbio', 'AS Gubbio 1910')
teams.set ('Pescara', 'Pescara Calcio')
teams.set ('Imolese', 'Imolese Calcio')
teams.set ('Entella', 'Virtus Entella')
teams.set ('Fermana', 'Fermana FC')
teams.set ('Carrarese', 'Carrarese Calcio 1908')
teams.set ('Viterbese', 'AS Viterbese Castrense')
teams.set ('Modena', 'Modena FC')
teams.set ('Pontedera', 'US Citta DI Pontedera')
teams.set ('Teramo', 'SS Teramo Calcio')
teams.set ('Reggiana', 'AC Reggiana 1919')
teams.set ('Lucchese', 'AS Lucchese Libertas 1905')
teams.set ('Pistoiese', 'US Pistoiese 1921')
teams.set ('Siena', 'AC Siena')
teams.set ('Cesena', 'AC Cesena')
teams.set ('Pesaro', 'SSD Vis Pesaro 1898')
teams.set ('Ancona', 'US Ancona 1905')
teams.set ('Albinoleffe', 'US Albinoleffe')
teams.set ('A.C. Trento S.C.S.D.', 'AC Trento')
teams.set ('Fiorenzuola', 'Fiorenzuola')
teams.set ('Giana Erminio', 'AS Giana Erminio')
teams.set ('Juventus B', 'Juventus U23')
teams.set ('FC Legnago', 'FC Legnago Salus Ssd')
teams.set ('Mantova', 'Mantova 1911')
teams.set ('Pro Vercelli', 'FC Pro Vercelli 1892')
teams.set ('Padova', 'Padova')
teams.set ('SS Virtus Verona 1921', 'Virt. Verona')
teams.set ('SSD Pro Sesto', 'SSD Pro Sesto')
teams.set ('Lecco', 'Calcio Lecco 1912')
teams.set ('Seregno Calcio', 'USD Seregno Calcio')
teams.set ('Piacenza', 'Piacenza Calcio 1919')
teams.set ('Triestina', 'US Triestina Calcio 1918')
teams.set ('Sudtirol', 'FC Sudtirol')
teams.set ('AP Turris Calcio', 'ASD Turris Calcio')
teams.set ('Paganese', 'Paganese Calcio 1926')
teams.set ('AZ Picerno ASD', 'AZ Picerno')
teams.set ('Taranto Sport', 'Taranto FC')
teams.set ('Juve Stabia', 'Juve Stabia')
teams.set ('Virtus Francavilla', 'Virtus Francavilla Calcio')
teams.set ('Monopoli', 'SS Monopoli 1966')
teams.set ('Andria BAT', 'Fidelis Andria')
teams.set ('Nuova Monterosi', 'Monterosi Tuscia')
teams.set ('US Latina Calcio', 'Latina Calcio')
teams.set ('Nuovo Campobasso', 'SSD Citta Di Campobasso')
teams.set ('Potenza', 'Potenza Calcio')
teams.set ('SSD Bari', 'SSC Bari')
teams.set ('Palermo', 'US Palermo')
teams.set ('Vibonese', 'US Vibonese Calcio')
teams.set ('Catanzaro', 'US Catanzaro 1929')
//Swiss Challenge League
teams.set ('Schaffhausen', 'Schaffhausen')
teams.set ('FC Wil', 'Wil 1900')
teams.set ('FC Vaduz', 'Vaduz')
teams.set ('Neuchatel Xamax', 'N. Xamax')
teams.set ('Aarau', 'Aarau')
teams.set ('Kriens', 'Kriens')
teams.set ('Stade Lausanne-Ouchy', 'Stade Ouchy')
teams.set ('Thun', 'Thun')
teams.set ('Yverdon Sport', 'Yverdon')
teams.set ('Winterthur', 'Winterthur')
//Swiss Super League
teams.set ('St Gallen', 'St. Gallen')
teams.set ('Lugano', 'Lugano')
teams.set ('FC Zurich', 'Zürih')
teams.set ('Sion', 'Sion')
teams.set ('Young Boys', 'Young Boys')
teams.set ('Servette', 'Servette')
teams.set ('Grasshoppers Zurich', 'Grasshoppers')
teams.set ('Lausanne', 'Lausanne')
teams.set ('FC Basel', 'Basel')
teams.set ('Luzern', 'Luzern')
//Japanese J League 2
teams.set ('Kumamoto', 'Roasso Kumamoto')
teams.set ('Okayama', 'Fagiano')
teams.set ('Thespakusatsu Gunma', 'Thespakusatsu Gunma')
teams.set ('Blaublitz Akita', 'Blaublitz Akita')
teams.set ('Sendai', 'Sendai')
teams.set ('FC Ryukyu', 'FC Ryukyu')
teams.set ('Tokyo-V', 'Tokyo Verdy')
teams.set ('Jef Utd Chiba', 'JEF United')
teams.set ('Kofu', 'Ventforet')
teams.set ('FC Machida', 'Machida Z')
teams.set ('Mito', 'M Hollyhock')
teams.set ('Renofa Yamaguchi', 'R Yamaguchi')
teams.set ('Tochigi SC', 'Tochigi')
teams.set ('Yokohama FC', 'Yokohama')
teams.set ('Albirex Niigata', 'Niigata')
teams.set ('Nagasaki', 'V-Varen')
teams.set ('Yamagata', 'M Yamagata')
teams.set ('Omiya', 'Omiya Ardija')
//Kazakhstan Premier League
teams.set ('FK Atyrau', 'FK Atyrau')
teams.set ('Tobol Kostanay', 'Tobol K')
teams.set ('FC Astana', 'FC Astana')
teams.set ('FK Kaspyi Aktau', 'FK Kaspyi Aktau')
teams.set ('Shakhter Karagandy', 'Shakhtar Karagandy')
teams.set ('FK Akzhajik', 'Akzhaiyk Uralsk')
teams.set ('FK Aktobe', 'FK Aktobe')
teams.set ('FK Maqtaaral Jetisay', 'FK Maktaaral')
teams.set ('FC Ordabasy', 'FC Ordabasy')
teams.set ('FK Kyzyl-Zhar', 'Kyzylžar Petropavlovsk')
teams.set ('Kairat Almaty', 'Kairat Almaty')
teams.set ('FC Turan', 'FK Turan')
teams.set ('FK Aksu Pavlodar', 'FK Aksu')
teams.set ('FK Taraz', 'Taraz')
//Finnish Veikkausliiga
teams.set ('Haka', 'Haka')
teams.set ('HIFK', 'HIFK')
teams.set ('Lahti', 'Lahti')
teams.set ('KuPS', 'Kuopion')
teams.set ('HJK Helsinki', 'HJK Helsinki')
teams.set ('FC Inter', 'Inter Turku')
teams.set ('Ilves', 'Tampereen')
teams.set ('VPS', 'Vaasan Ps')
teams.set ('Honka', 'FC Honka')
teams.set ('SJK', 'Seinöjoen')
teams.set ('IFK Mariehamn', 'Mariehamn')
teams.set ('AC Oulu', 'Oulu')
//Estonian Premier League
teams.set ('Tallinna JK Legion', 'Tallinna JK Legion')
teams.set ('Parnu JK Vaprus', 'Parnu JK Vap')
teams.set ('Tallinna FC Flora', 'Flora Tall')
teams.set ('Fci Tallinn', 'Levadia Tall')
teams.set ('Nomme Kalju', 'Nomme Kalju')
teams.set ('Trans Narva', 'Trans Narva')
teams.set ('Tallinna Kalev', 'Tallinna Kal')
teams.set ('Tammeka Tartu', 'Tartu JK Tam')
teams.set ('Kuressaare', 'Kuressaare')
teams.set ('Paide Linnameeskond', 'Paide Flora')
//Croatian 1 HNL
teams.set ('NK Hrvatski Dragovoljac', 'NK Hrvatski Dragovoljac')
teams.set ('Sibenik', 'HNK Sibenik')
teams.set ('Rijeka', 'Rijeka')
teams.set ('Osijek', 'Osijek')
teams.set ('HNK Gorica', 'HNK Gorica')
teams.set ('Dinamo Zagreb', 'Dinamo Zagreb')
teams.set ('NK Istra', 'NK Istra 61')
teams.set ('Lokomotiva', 'L. Zagreb')
teams.set ('Slaven Belupo', 'NK Slaven')
teams.set ('Hajduk Split', 'Hajduk Split')
//Polish I Liga
teams.set ('LKS Lodz', 'LKS Lodz')
teams.set ('Chrobry Glogow', 'C Glogow')
teams.set ('Resovia Rzeszow', 'Resovia')
teams.set ('Zaglebie Sosnowiec', 'Z Sosnowiec')
teams.set ('Korona Kielce', 'Korona Kielce')
teams.set ('Arka Gdynia', 'Arka Gdynia')
teams.set ('GKS Jastrzebie', 'Jastrzebie')
teams.set ('Widzew Lodz', 'Widzew Lodz')
teams.set ('Puszcza Niepolomice', 'Puszcza')
teams.set ('Gornik Polkowice', 'Polkowice')
teams.set ('Miedz Legnica', 'M. Legnica')
teams.set ('Sandecja Nowy Sacz', 'Sandecja')
teams.set ('GKS Tychy', 'GKS Tychy')
teams.set ('GKS Katowice', 'Katowice')
teams.set ('Skra Czestochowa', 'Czestochowa')
teams.set ('Odra Opole', 'Odra Opole')
teams.set ('Podbeskidzie B-B', 'P. Bielsko')
teams.set ('Stomil Olsztyn', 'Stomil Ols.')
//Polish Ekstraklasa
teams.set ('Zaglebie Lubin', 'Zaglebie Lubin')
teams.set ('Gornik Zabrze', 'Gornik Zabrze')
teams.set ('Radomiak Radom', 'Radomiak Rad')
teams.set ('Cracovia Krakow', 'Cracovia')
teams.set ('Slask Wroclaw', 'Slask Wroclaw')
teams.set ('Nieciecza', 'Nieciecza')
teams.set ('Lech Poznan', 'Lech Poznan')
teams.set ('Stal Mielec', 'Stal Mielec')
teams.set ('Piast Gliwice', 'Piast Gliwice')
teams.set ('Jagiellonia Bialystock', 'Jagiellonia Bialystok')
teams.set ('Lechia Gdansk', 'Lechia Gdansk')
teams.set ('Warta Poznan', 'Warta Poznan')
teams.set ('Rakow Czestochowa', 'Rakow Czestochowa')
teams.set ('Gornik Leczna', 'G. Leczna')
teams.set ('Pogon Szczecin', 'Pogon Szczecin')
teams.set ('Legia Warsaw', 'Legia Varşova')
teams.set ('Wisla Krakow', 'Wisla Krakow')
teams.set ('Wisla Plock', 'Wisla Plock')
//Slovenian 2 SNL
teams.set ('Nafta Lendava', 'Nafta')
teams.set ('Gorica', 'ND Gorica')
teams.set ('Drava (Slovenia)', 'NS Drava')
teams.set ('NK Fuzinar', 'NK Fuzinar')
teams.set ('Krsko', 'NK Krsko')
teams.set ('Triglav', 'Triglav')
teams.set ('Roltek Dob', 'Roltek Dob')
teams.set ('Ilirija Extra-Lux', 'NK Ilirija')
teams.set ('Rudar', 'Rudar')
teams.set ('NK Bilje', 'NK Bilje')
//Slovenian Premier League
teams.set ('Tabor Sezana', 'Tabor Sezana')
teams.set ('NK Maribor', 'NK Maribor')
teams.set ('NK Radomlje', 'NK Radomlje')
teams.set ('Mura', 'NS Mura')
teams.set ('NK Bravo', 'NK Bravo')
teams.set ('Domzale', 'NK Domzale')
teams.set ('Koper', 'FC Koper')
teams.set ('Olimpija', 'O. Ljubljana')
teams.set ('NK Aluminij', 'NK Aluminij Kidricevo')
teams.set ('NK Celje', 'NK Celje')
//Austrian Erste Liga
teams.set ('FC Wacker Innsbruck', 'Wacker Innsbruck')
teams.set ('Rapid Vienna (Am)', 'SK Rapid Wien (A)')
teams.set ('SKU Amstetten', 'SKU Amstetten')
teams.set ('SV Horn', 'SV Horn')
teams.set ('Ksv 1919', 'Kapfenberger SV 1919')
teams.set ('SC AUSTRIA LUSTENAU', 'Aus Lustenau')
teams.set ('Austria Wien (A)', 'Austria Wien II')
teams.set ('FC Blau Weiss Linz', 'Blau Weiss Linz')
teams.set ('FC Dornbirn', 'Dornbirn')
teams.set ('SV Lafnitz', 'SV Lafnitz')
teams.set ('SK Vorwarts Steyr', 'Vorwarts')
teams.set ('Floridsdorfer Ac', 'Floridsdorfer')
teams.set ('Grazer AK', 'Grazer AK')
teams.set ('St Polten', 'St. Pölten')
//Austrian Bundesliga
teams.set ('Admira Wacker', 'Admira Wacker')
teams.set ('Hartberg', 'Hartberg')
teams.set ('LASK Linz', 'LASK')
teams.set ('SCR Altach', 'Altach')
teams.set ('WSG Wattens', 'WSG Tirol')
teams.set ('SV Ried', 'SV Ried')
teams.set ('Austria Klagenfurt', 'Klagenfurt')
teams.set ('Wolfsberger AC', 'Wolfsberg')
teams.set ('Red Bull Salzburg', 'Salzburg')
teams.set ('Austria Vienna', 'Austria Wien')
teams.set ('Rapid Vienna', 'Rapid Wien')
teams.set ('Sturm Graz', 'Sturm Graz')
//Danish 1st Division
teams.set ('FC Helsingor', 'Helsingoer')
teams.set ('Hvidovre', 'Hvidovre')
teams.set ('Fredericia', 'Fredericia')
teams.set ('Lyngby', 'Lyngby BK')
teams.set ('Jammerbught FC', 'Jammerbugt')
teams.set ('Vendsyssel FF', 'Vendsyssel')
teams.set ('Esbjerg', 'Esbjerg')
teams.set ('HB Koge', 'HB Koege')
teams.set ('AC Horsens', 'AC Horsens')
teams.set ('Nykobing FC', 'Nykoebing')
//Danish Superliga
teams.set ('Brondby', 'Brondby')
teams.set ('Midtjylland', 'Midtjylland')
teams.set ('AGF', 'AGF Aarhus')
teams.set ('OB', 'Odense')
teams.set ('SonderjyskE', 'Sonderjyske')
teams.set ('Vejle', 'Vejle')
teams.set ('FC Nordsjaelland', 'Nordsjælland')
teams.set ('Viborg', 'Viborg')
teams.set ('FC Copenhagen', 'Kopenhag')
teams.set ('Randers', 'Randers')
teams.set ('AaB', 'Aalborg BK')
teams.set ('Silkeborg', 'Silkeborg')
//Swedish Division 1
teams.set ('Tvaakers', 'Tvaakers')
teams.set ('Angelholms', 'Angelholms')
teams.set ('Umea FC', 'Umea')
teams.set ('Gefle', 'Gefle')
teams.set ('IFK Malmo', 'IFK Malmö')
teams.set ('BK Olympic', 'BK Olympic')
teams.set ('Orebro Syrianska', 'Orebro Syri')
teams.set ('Hammarby TFF', 'Hammarby Talang FF')
teams.set ('Sandvikens', 'Sandvikens')
teams.set ('Vasalunds IF', 'V Essinge')
teams.set ('Lindome', 'Lindome')
teams.set ('Oddevold', 'IK Oddevold')
teams.set ('Lunds BK', 'Lunds BK')
teams.set ('FC Trollhattan', 'Trollhattan')
teams.set ('IF Karlstad', 'IF Karlstad Fotboll')
teams.set ('Pitea', 'Pitea')
teams.set ('Qviding FIF', 'Qviding F')
teams.set ('Oskarshamns AIK', 'Oskarshmans')
teams.set ('Taby FK', 'Taby FK')
teams.set ('BK Forward', 'BK Forward')
teams.set ('IF Sylvia', 'Sylvia')
teams.set ('IFK Haninge', 'IFK Haninge')
teams.set ('FC Stockholm Internazionale', 'Stockholm In')
teams.set ('Team TG FF', 'Team Tg')
teams.set ('GAIS', 'Gais')
teams.set ('Aatvidabergs FF', 'Atvidabergs')
//Swedish Division 2
teams.set ('Hassleholms IF', 'Hassleholms IF')
teams.set ('Rappe GOIF', 'Rappe Goif')
teams.set ('Landvetter IS', 'Landvetter IS')
teams.set ('Torslanda', 'Torslanda')
//Swedish Superettan
teams.set ('Jonkopings Sodra', 'Jönköping')
teams.set ('Trelleborgs', 'Trelleborgs')
teams.set ('Utsiktens', 'Utsiktens')
teams.set ('AFC Eskilstuna', 'Eskilstuna')
teams.set ('Skovde AIK', 'Skövde')
teams.set ('Norrby IF', 'Norrby')
teams.set ('IK Brage', 'IK Brage')
teams.set ('Brommapojkarna', 'Brommapojkarna')
teams.set ('Landskrona', 'Landskrona')
teams.set ('Orgryte', 'Orgryte')
teams.set ('Osters', 'Osters')
teams.set ('Vasteras SK', 'Vasteraas')
teams.set ('Orebro', 'Orebro SK')
teams.set ('Halmstads', 'Halmstads BK')
//Swedish Allsvenskan
teams.set ('AIK', 'AIK Solna')
teams.set ('Djurgardens', 'Djurgardens')
teams.set ('Varbergs BoIS', 'Varbergs')
teams.set ('Mjallby', 'Mjallby')
teams.set ('Helsingborgs', 'Helsingborg')
teams.set ('Hacken', 'Hacken')
teams.set ('Elfsborg', 'IF Elfsborg')
teams.set ('Sundsvall', 'Sundsvall')
teams.set ('Sirius', 'IK Sirius')
teams.set ('Hammarby', 'Hammarby')
teams.set ('Varnamo', 'IFK Varnamo')
teams.set ('Degerfors', 'Degerfors IF')
teams.set ('Malmo FF', 'Malmö')
teams.set ('IFK Goteborg', 'Göteborg')
teams.set ('Kalmar FF', 'Kalmar')
teams.set ('Norrkoping', 'Norrköping')
teams.set ('Djurgardens', 'Djurgardens')
teams.set ('Sirius', 'Sirius')
//Dutch Eredivisie
teams.set ('FC Twente', 'Twente')
teams.set ('Sparta Rotterdam', 'Sparta Rotterdam')
teams.set ('Az Alkmaar', 'AZ Alkmaar')
teams.set ('Heerenveen', 'Heerenveen')
teams.set ('Feyenoord', 'Feyenoord')
teams.set ('FC Utrecht', 'Utrecht')
teams.set ('RKC Waalwijk', 'Waalwijk')
teams.set ('PEC Zwolle', 'Zwolle')
teams.set ('NEC Nijmegen', 'NEC Nijmegen')
teams.set ('Ajax', 'Ajax')
teams.set ('Cambuur Leeuwarden', 'SC Cambuur')
teams.set ('PSV', 'PSV')
teams.set ('Fortuna Sittard', 'Fortuna Sittard')
teams.set ('Go Ahead Eagles', 'Go Ahead')
teams.set ('FC Groningen', 'Groningen')
teams.set ('Heracles', 'Heracles')
teams.set ('Willem II', 'Willem II')
teams.set ('Vitesse Arnhem', 'Vitesse')
//Dutch Eerste Divisie
teams.set ('FC Oss', 'TOP Oss')
teams.set ('Almere City', 'Almere City')
teams.set ('Emmen', 'Emmen')
teams.set ('Roda JC', 'Roda')
teams.set ('SC Telstar', 'Telstar')
teams.set ('FC Eindhoven', 'Eindhoven')
teams.set ('Excelsior', 'Excelsior')
teams.set ('Jong AZ Alkmaar', 'Jong Alkmaar')
teams.set ('NAC Breda', 'NAC Breda')
teams.set ('FC Dordrecht', 'Dordrecht')
teams.set ('Helmond Sport', 'Helmond')
teams.set ('De Graafschap', 'Graafschap')
teams.set ('Den Bosch', 'Den Bosch')
teams.set ('FC Volendam', 'Volendam')
teams.set ('ADO Den Haag', 'ADO Den Haag')
teams.set ('Jong FC Utrecht', 'Jong Utrecht')
teams.set ('Jong Ajax', 'Jong Ajax')
teams.set ('VVV Venlo', 'VVV Venlo')
teams.set ('Jong PSV', 'Jong PSV')
teams.set ('Maastricht', 'Maastricht')
//Hungarian NB I
teams.set ('MTK Budapest', 'MTK Budapeşte')
teams.set ('Mezokovesd-Zsory', 'Mezokovesd Z')
teams.set ('Zalaegerszeg', 'Zalaegerszeg')
teams.set ('Paks', 'Paksi')
teams.set ('MOL Vidi', 'Fehervar')
teams.set ('Puskas Akademia', 'Puskas Akad')
teams.set ('Kisvarda', 'Kisvarda')
teams.set ('DEBRECENI VSC', 'Debrecen')
teams.set ('Ferencvaros', 'Ferencvaros')
teams.set ('Ujpest', 'Ujpest')
teams.set ('Gyirmot', 'Gyirmot FC Gyor')
teams.set ('Honved', 'Bud. Honved')
//Peruvian Primera Division
teams.set ('Cienciano', 'CS Cienciano')
teams.set ('Sporting Cristal', 'Sporting Cristal')
teams.set ('Ayacucho Futbol Club', 'Ayacucho FC')
teams.set ('Atletico Grau', 'Atletico Grau')
teams.set ('Deportivo Municipal', 'D. Municipal')
teams.set ('Melgar', 'Melgar')
teams.set ('AD Cantolao', 'Academia Cantolao')
teams.set ('Alianza Lima', 'Alianza Lima')
teams.set ('Binacional', 'Deportivo Binacional')
teams.set ('Carlos Mannucci', 'Carlos Mannucci')
teams.set ('C Stein', 'FC Carlos Stein')
teams.set ('UTC Cajamarca', 'Cajamarca')
teams.set ('Uni San Martin', 'CD Usmp')
teams.set ('Sport Huancayo', 'Huancayo')
teams.set ('Asociacion Deportiva Tarma', 'Asociacion Deportiva Tarm')
teams.set ('Alianza Atletico', 'Alianza Atletico')
teams.set ('Universitario de Deportes', 'U. Deportes')
teams.set ('Sport Boys (Per)', 'Sport Boys')
//Portuguese Primeira Liga
teams.set ('Vizela', 'FC Vizela')
teams.set ('Arouca', 'FC Arouca')
teams.set ('Benfica', 'Benfica')
teams.set ('Famalicao', 'Famalicao')
teams.set ('Portimonense', 'Portimonense')
teams.set ('Moreirense', 'Moreirense')
teams.set ('Tondela', 'CD Tondela')
teams.set ('Guimaraes', 'Vitoria Guimaraes')
teams.set ('Boavista', 'Boavista')
teams.set ('Sporting Lisbon', 'Sporting Lizbon')
teams.set ('Santa Clara', 'Santa Clara')
teams.set ('Maritimo', 'Maritimo')
teams.set ('Gil Vicente', 'Gil Vicente')
teams.set ('Pacos Ferreira', 'P. Ferreira')
teams.set ('Estoril Praia', 'Estoril Praia')
teams.set ('Belenenses', 'Belenenses')
teams.set ('Braga', 'Braga')
teams.set ('Porto', 'Porto')
//Portuguese Segunda Liga
teams.set ('Chaves', 'Chaves')
teams.set ('Academica', 'Academica')
teams.set ('CD Nacional Funchal', 'N. Madeira ')
teams.set ('Farense', 'Sporting Farense')
teams.set ('Benfica B', 'Benfica B')
teams.set ('Academico de Viseu', 'A. de Viseu')
teams.set ('Casa Pia', 'Casa Pia AC')
teams.set ('Club Football Estrela', 'CF Estrela')
teams.set ('Penafiel', 'Penafiel')
teams.set ('Feirense', 'CD Feirense')
teams.set ('Mafra', 'CD Mafra')
teams.set ('Rio Ave', 'Rio Ave')
teams.set ('Covilha', 'SC Covilha')
teams.set ('Leixoes', 'Leixoes SC')
teams.set ('Porto B', 'Porto B')
teams.set ('Vilafranquense', 'UD Vilafranquense')
//Bolivian Liga de Futbol Profesional
teams.set ('Bolivar', 'Club Bolivar')
teams.set ('Independiente Petrolero', 'Independiente Petrolero')
teams.set ('Jorge Wilstermann', 'J Wilsterman')
teams.set ('Universitario de Vinto', 'FC Universitario de Vinto')
teams.set ('Real Tomayapo', 'Cd Real Tomayapo')
teams.set ('Always Ready', 'Always Ready')
teams.set ('Blooming Santa Cruz', 'Blooming')
teams.set ('Royal Pari', 'Royal Pari S')
teams.set ('Universitario (Sucre)', 'Universitario de Sucre')
teams.set ('The Strongest', 'Strongest')
teams.set ('Atletico Palmaflor Vinto', 'Atletico Palmaflor Vinto')
teams.set ('Aurora', 'Club Aurora')
teams.set ('Club Real Santa Cruz', 'Real Santa Cruz')
teams.set ('Nacional Potosi', 'Nacional Potosi')
teams.set ('Guabira', 'Guabira Montero')
teams.set ('Oriente Petrolero', 'Oriente Petrolero')
//Brazilian Serie B
teams.set ('Chapecoense', 'Chapecoense')
teams.set ('Vasco Da Gama', 'Vasco Da Gama')
teams.set ('CSA', 'CSA AL')
teams.set ('Bahia', 'Bahia BA')
teams.set ('Tombense MG', 'Tombense FC MG')
teams.set ('Cruzeiro MG', 'Cruzeiro MG')
teams.set ('Criciuma', 'Criciuma')
teams.set ('Sport Recife', 'Recife')
teams.set ('Sampaio Correa FC', 'Samp. Correa')
teams.set ('Brusque FC', 'Brusque Sc')
teams.set ('Ponte Preta', 'Ponte Preta')
teams.set ('CRB', 'Crb Al')
teams.set ('Nautico PE', 'Nautico PE')
teams.set ('Operario PR', 'Operario')
teams.set ('Ituano', 'Ituano FC SP')
teams.set ('Vila Nova', 'Vila Nova')
//Brazilian Serie A
teams.set ('Athletico-PR', 'Paranaense')
teams.set ('Flamengo', 'Flamengo')
teams.set ('Bragantino SP', 'Bragantino SP')
teams.set ('Sao Paulo', 'Sao Paulo SP')
teams.set ('Fluminense', 'Fluminense')
teams.set ('Internacional', 'Internacional')
teams.set ('SE Palmeiras', 'Palmeiras SP')
teams.set ('Corinthians', 'Corinthians')
teams.set ('Atletico MG', 'Atletico Mineiro')
teams.set ('Coritiba', 'Coritiba')
teams.set ('Santos', 'Santos SP')
teams.set ('America MG', 'America MG')
teams.set ('Juventude', 'Juventude')
teams.set ('Cuiaba', 'Cuiaba')
teams.set ('Atletico Go', 'Goianiense')
teams.set ('Botafogo', 'Botafogo RJ')
teams.set ('Avai', 'Avai SC')
teams.set ('Goias', 'Goias GO')
//Brazilian Serie C
teams.set ('Brasil de Pelotas', 'Gremio Esportivo Brazil')
teams.set ('Botafogo SP', 'Botafogo')
teams.set ('Botafogo PB', 'Botafogo PB')
teams.set ('Confianca', 'Confianca')
teams.set ('FC Atletico Cearense', 'Atletico Cearense')
teams.set ('Ferroviario', 'Ferroviario')
teams.set ('Remo', 'Clube DO Remo PA')
teams.set ('EC Sao Jose Porto Alegre', 'EC Sao Jose')
teams.set ('ABC RN', 'Abc FC RN')
teams.set ('Campinense', 'Campinense PB')
teams.set ('Volta Redonda', 'Volta Redonda FC RJ')
teams.set ('Altos', 'AA Altos PI')
teams.set ('Figueirense', 'Figueirense FC SC')
teams.set ('Manaus FC', 'Manaus FC AM')
teams.set ('Aparecidense Go', 'AA Aparecidense GO')
teams.set ('Ypiranga RS', 'Ypiranga FC RS')
teams.set ('EC Vitoria Salvador', 'EC Vitoria BA')
teams.set ('Mirassol', 'Mirassol FC SP')
teams.set ('Paysandu', 'Paysandu SC PA')
//Venezuelan Primera Division
teams.set ('Caracas', 'Caracas')
teams.set ('Deportivo Tachira', 'Depo Tachira')
teams.set ('Zamora FC', 'Zamora')
teams.set ('Metropolitanos', 'Metropolitan')
teams.set ('Deportivo Lara', 'Guaros Lara')
teams.set ('Puerto Cabello', 'Academia Puerto Cabello')
teams.set ('Monagas', 'Monagas SC')
teams.set ('Universidad de Venezuela', 'Ucv FC')
teams.set ('Estudiantes de Merida', 'Estudiante M')
teams.set ('CD Hermanos Colmenarez', 'CD Hermanos Colmenarez')
teams.set ('Mineros Guayana', 'Miner Guayan')
teams.set ('Zulia', 'Zulia')
//Uruguayan Primera Division
teams.set ('Cerro Largo FC', 'Cerro Largo FC')
teams.set ('Nacional (Uru)', 'Nacional')
teams.set ('Torque', 'Torque')
teams.set ('Penarol', 'Penarol Uru')
teams.set ('Wanderers (Uru)', 'Montevideo')
teams.set ('Liverpool Montevideo', 'Liverpool Montevideo')
teams.set ('River Plate (Uru)', 'River Plate (Uru)')
teams.set ('Danubio', 'Danubio FC')
teams.set ('Centro Atletico Fenix', 'Atletico Fenix Montevideo')
teams.set ('Albion FC', 'Albion FC')
teams.set ('Boston River', 'Boston River')
teams.set ('Deportivo Maldonado', 'Deportivo Maldonado')
teams.set ('Plaza Colonia', 'Plaza Colonia')
teams.set ('CA Rentistas', 'Club Atletico Rentistas')
teams.set ('Defensor Sporting', 'Defensor Sporting')
teams.set ('Cerrito', 'CS Cerrito')
//Mexican Liga MX
teams.set ('Puebla', 'Puebla')
teams.set ('Necaxa', 'Necaxa')
teams.set ('FC Juarez', 'FC Juarez')
teams.set ('Mazatlan FC', 'Mazatlan')
teams.set ('Guadalajara', 'Guadalajara Chivas')
teams.set ('Pumas UNAM', 'Pumas Unam')
teams.set ('Tijuana', 'XolosTijuana')
teams.set ('Queretaro', 'Queretaro')
teams.set ('Toluca', 'Deportivo Toluca')
teams.set ('Atlas', 'Atlas FC')
teams.set ('Pachuca', 'CF Pachuca')
teams.set ('Monterrey', 'CF Monterrey')
teams.set ('Tigres', 'Tigres')
teams.set ('CF America', 'CF America')
teams.set ('Cruz Azul', 'Cruz Azul')
teams.set ('San Luis', 'At. San Luis')
teams.set ('Santos Laguna', 'Santos Laguna')
teams.set ('Leon', 'Club Leon')
//Czech 2 Liga
teams.set ('SFC Opava', 'Opava')
teams.set ('Pribram', 'Pribram')
teams.set ('Vyskov', 'MFK Vyskov')
teams.set ('FC Zbrojovka Brno', 'Brno')
teams.set ('FC Sellier & Bellot Vlasim', 'S&B Vlasim')
teams.set ('Usti Nad Labem', 'Usti Nad Lab')
teams.set ('MFK Chrudim', 'MFK Chrudim')
teams.set ('Zizkov', 'Vik. Zizkov')
teams.set ('Vysocina Jihlava', 'Jihlava')
teams.set ('Prostejov', '1.SK Prostej')
teams.set ('Dukla Prague', 'Dukla Prag')
teams.set ('Varnsdorf', 'FK Varnsdorf')
teams.set ('Trinec', 'Trinec')
teams.set ('Sparta Prague B', 'AC Sparta Prague B')
teams.set ('Lisen', 'SK Lisen')
teams.set ('MAS Taborsko', 'Taborsko')
//Slovakian Super League
teams.set ('Dunajska Streda', 'Dunajska S')
teams.set ('Slovan Bratislava', 'Slovan Bratislava')
teams.set ('Tatran Lip Mikulas', 'Liptovsky M')
teams.set ('Pohronie', 'Pohronie')
teams.set ('Zilina', 'MSK Zilina')
teams.set ('SK Sered', 'SKF Sered')
teams.set ('Zlate Moravce', 'VZ Moravce V')
teams.set ('Trencin', 'AS Trencin')
teams.set ('Spartak Trnava', 'Spartak Trna')
teams.set ('Ruzomberok', 'Ruzomberok')
//Slovakian 2 Liga
teams.set ('Slovan Bratislava II', 'Slovan Bratislava B')
teams.set ('FK Humenne', 'FK Humenne')
teams.set ('Dubnica', 'FK Dubnica Nad Vahom')
teams.set ('MFK Skalica', 'MFK Skalica')
teams.set ('FK Puchov', 'FK Puchov')
teams.set ('Namestovo', 'MSK Namestovo')
teams.set ('KFC Komarno', 'KFC Komarno')
teams.set ('Samorin', 'Stk Samorin')
teams.set ('Partizan Bardejov', 'Partizan Bardejov')
teams.set ('FC Rohoznik', 'FC Rohoznik')
teams.set ('Slavoj Trebisov', 'S Trebisov')
teams.set ('Podbrezova', 'FK Zeleziarne Podbrezova')
//Romanian Liga I
teams.set ('Chindia Targoviste', 'Chindia')
teams.set ('Rapid Bucharest', 'Rapid 1923')
teams.set ('ACS Sepsi OSK', 'Sepsi Os Sf')
teams.set ('FC Voluntari', 'Voluntari')
teams.set ('CFR Cluj', 'Cluj')
teams.set ('Botosani', 'Botosani')
teams.set ('FC U Craiova 1948', 'U Craiova')
teams.set ('Argeș Pitești', 'A. Pitesti')
teams.set ('Universitatea Craiova', 'Un. Craiova')
teams.set ('Farul Constanta', 'Farul Cons.')
teams.set ('FCSB', 'FCSB')
//Norwegian 1st Division
teams.set ('Brann', 'Brann')
teams.set ('Sogndal', 'Sogndal IL')
teams.set ('Raufoss', 'Raufoss')
teams.set ('Grorud IL', 'Grorud IL')
teams.set ('Stjordals-Blink', 'STOR/BLINK')
teams.set ('KFUM Oslo', 'Kfum Oslo')
teams.set ('Bryne', 'Bryne')
teams.set ('Ranheim IL', 'Ranheim')
teams.set ('Start', 'IK Start')
teams.set ('Skeid', 'Skeid')
teams.set ('Kongsvinger', 'Kongsvinger')
teams.set ('Asane', 'Asane')
teams.set ('Mjondalen', 'Mjondalen')
teams.set ('Fredrikstad', 'Fredrikstad')
teams.set ('Stabaek', 'Stabaek')
teams.set ('Sandnes Ulf', 'Sandnes ULF')
//Norwegian 2nd Division
teams.set ('Oygarden FK', 'Oeygarden FK')
teams.set ('Vard Haugesund', 'Va.Haugesund')
teams.set ('Baerum', 'Baerum')
teams.set ('Eidsvold Turn', 'Eidsvold TF')
teams.set ('Orn Horten', 'Orn Horten')
teams.set ('Egersund', 'Egersunds')
teams.set ('Brattvag', 'Brattvag')
teams.set ('Levanger', 'Levanger')
teams.set ('Gjovik-Lyn', 'Gjovik-Lyn')
teams.set ('Traeff', 'Traeff')
teams.set ('Kjelsas', 'Kjelsas')
teams.set ('Frigg', 'Frigg')
teams.set ('Floy Flekkeroy', 'Flekkeroy')
teams.set ('Kvik Halden', 'Kvik Halden')
teams.set ('Tromsdalen', 'Tromsdalen')
teams.set ('Hodd', 'Hodd IL')
teams.set ('Strommen', 'Strommen')
teams.set ('Sotra SK', 'Sotra SK')
teams.set ('Arendal', 'FK Arendal')
teams.set ('Staal Jorpeland', 'Staal Joerpeland')
teams.set ('Moss', 'Moss FK')
teams.set ('Ullern', 'Ullern')
//Norwegian Eliteserien
teams.set ('Stromsgodset', 'Stromsgodset')
teams.set ('Haugesund', 'Haugesund')
teams.set ('Viking', 'Viking')
teams.set ('Bodo Glimt', 'Bodo Glimt')
teams.set ('Valerenga', 'Valerenga')
teams.set ('Jerv', 'Jerv')
teams.set ('Rosenborg', 'Rosenborg')
teams.set ('Molde', 'Molde')
teams.set ('Odds BK', 'Odds BK')
teams.set ('Aalesunds', 'Aalesunds')
teams.set ('Kristiansund', 'Kristiansund')
teams.set ('Ham-Kam', 'H.kameratene')
teams.set ('Tromso', 'Tromso IL')
teams.set ('Sarpsborg', 'Sarpsborg 08')
teams.set ('Lillestrom', 'Lillestrom ')
teams.set ('Sandefjord', 'Sandefjord')
//Swiss Super League
teams.set ('FC Zurich', 'Zürih')
teams.set ('Sion', 'Sion')
teams.set ('Young Boys', 'Young Boys')
teams.set ('Servette', 'Servette')
teams.set ('St Gallen', 'St. Gallen')
teams.set ('Lugano', 'Lugano')
teams.set ('FC Basel', 'Basel')
teams.set ('Luzern', 'Luzern')
teams.set ('Grasshoppers Zurich', 'Grasshoppers')
teams.set ('Lausanne', 'Lausanne')
//Swiss Challenge League
teams.set ('Schaffhausen', 'Schaffhausen ')
teams.set ('FC Wil', 'Wil 1900')
teams.set ('FC Vaduz', 'Vaduz')
teams.set ('Neuchatel Xamax', 'N. Xamax')
teams.set ('Aarau', 'Aarau')
teams.set ('Kriens', 'Kriens')
teams.set ('Stade Lausanne-Ouchy', 'Stade Ouchy')
teams.set ('Thun', 'Thun')
teams.set ('Yverdon Sport', 'Yverdon')
teams.set ('Winterthur', 'Winterthur')
//Bosnian Premier League
teams.set ('Siroki Brijeg', 'Siroki Brije')
teams.set ('Rudar Prijedor', 'FK Rudar Prijedor')
teams.set ('Sloboda Tuzla', 'FK Sloboda Tuzla')
teams.set ('Leotar Trebinje', 'FK Leotar Trebinje')
teams.set ('Sarajevo', 'Sarajevo')
teams.set ('Tuzla City', 'Tuzla City')
teams.set ('Borac Banja Luka', 'Banja Luka')
teams.set ('Radnik Bijeljina', 'Rad. Bijelji')
teams.set ('FK Velez Mostar', 'Velez Mostar')
teams.set ('Nk Posusje', 'NK Posusje')
//Maltese Premier League
teams.set ('Balzan FC', 'Balzan FC')
teams.set ('Valletta', 'Valetta')
teams.set ('Birkirkara', 'Birkirkara FC')
teams.set ('Floriana', 'Floriana')
teams.set ('Sliema Wanderers FC', 'Sliema Wanderers')
teams.set ('Sirens FC', 'Sirens FC')
//Argentinian Primera B Nacional
teams.set ('Brown de Adrogue', 'CA Brown De Adrogue')
teams.set ('Independiente Rivadavia', 'Ind. Mendoza')
teams.set ('CA Atlanta', 'CA Atlanta')
teams.set ('Estudiantes Rio Cuarto', 'Estudiantes Río Cuarto')
teams.set ('San Telmo', 'San Telmo')
teams.set ('CA Temperley', 'Club Atletico Temperley')
teams.set ('Chacarita', 'Chacarita Juniors')
teams.set ('Quilmes', 'Quilmes Atletico Club')
teams.set ('San Martin de San Juan', 'S Martin SJ')
teams.set ('Deportivo Madryn', 'Deportivo Madryn')
teams.set ('Tristan Suarez', 'T. Suarez')
teams.set ('Sacachispas', 'Sacachispas')
teams.set ('Santamarina', 'CD Santamarina Tandil')
teams.set ('Almagro BA', 'Almagro')
teams.set ('All Boys', 'All Boys')
teams.set ('Gimnasia Jujuy', 'Gimnasia Y Esgrima Jujuy')
teams.set ('Chaco For Ever', 'Chaco For Ever')
teams.set ('Deportivo Moron', 'Deportivo Moron')
teams.set ('Atletico Rafaela', 'Atletico De Rafaela')
teams.set ('Nueva Chicago', 'Nueva Chicago')
teams.set ('Estudiantes de Caseros', 'Estudiantes Caseros')
teams.set ('Alvarado', 'CA Alvarado')
teams.set ('Guillermo Brown', 'Guillermo Brown')
teams.set ('CD MAIPU', 'CD Maipu')
teams.set ('CA Guemes', 'CA Guemes')
teams.set ('Almirante Brown', 'Club Almirante Brown')
//Belgian First Division A
teams.set ('Yellow-Red Mechelen', 'Mechelen')
teams.set ('Charleroi', 'Charleroi')
teams.set ('Club Brugge', 'Club Brugge')
teams.set ('Antwerp', 'Antwerp')
teams.set ('Gent', 'KAA Gent')
teams.set ('Genk', 'KRC Genk')
teams.set ('Union St Gilloise', 'U S-Gilloise')
teams.set ('Anderlecht', 'Anderlecht')
//Ecuadorian Serie A
teams.set ('Gualaceo SC', 'Gualaceo SC')
teams.set ('Orense Sporting Club', 'Orense SC')
teams.set ('Deportivo Cuenca', 'CD Cuenca')
teams.set ('Club Nueve de Octubre', '9 de Octubre FC')
teams.set ('Delfin', 'Delfin Sc')
teams.set ('Independiente (Ecu)', 'Independiente Del Valle')
teams.set ('Univ Catolica (Ecu)', 'Uni Catolica')
teams.set ('Tecnico Universitario', 'Tecnico Universitario')
teams.set ('LDU', 'LDU Quito')
teams.set ('Mushuc Runa', 'Mushuc Runa')
teams.set ('Emelec', 'CS Emelec')
teams.set ('Aucas', 'SD Aucas')
teams.set ('Macara', 'CSD Macara')
teams.set ('Barcelona (Ecu)', 'Barcelona SC')
teams.set ('Guayaquil City', 'Guayaquil Ct')
teams.set ('Cumbaya FC', 'Cumbaya FC')
//Colombian Primera A
teams.set ('Atletico Bucaramanga', 'A. Bucaraman')
teams.set ('Ind Medellin', 'Indep.Medell')
teams.set ('Atletico Nacional Medellin', 'Atl Nacional')
teams.set ('Once Caldas', 'Once Caldas')
teams.set ('Union Magdalena', 'U. Magdalena')
teams.set ('Junior FC Barranquilla', 'Atl. Junior')
teams.set ('Envigado', 'Envigado FC')
teams.set ('Deportivo Pereira', 'CS Deportivo Pereira')
teams.set ('Deportivo Cali', 'Deport Cali')
teams.set ('Rionegro', 'R Aguilas')
teams.set ('Jaguares de Cordoba', 'Jaguares De')
teams.set ('America de Cali S.A', 'America Cali')
teams.set ('Millonarios', 'Millonarios')
teams.set ('Santa Fe', 'Independiente Santa Fe')
teams.set ('Alianza Petrolera', 'Alianza Ptr.')
teams.set ('Tolima', 'Deportes Tol')
teams.set ('Cortulua', 'CD Cortulua')
teams.set ('La Equidad', 'D.La Equidad')
teams.set ('Deportivo Pasto', 'Deport Pasto')
teams.set ('Boyaca Patriotas', 'Boyaca Patr.')
//Colombian Primera B
teams.set ('Orsomarso', 'Orsomarso SC')
teams.set ('Bogota', 'Bogota FC')
teams.set ('Llaneros FC', 'Llaneros FC')
teams.set ('Leones FC', 'Itagui Leones FC')
teams.set ('Valledupar', 'Valledupar FC')
teams.set ('Atletico Huila', 'CD Atletico Huila')
teams.set ('Boca Juniors de Cali', 'Boca Juniors De Cali')
teams.set ('Real Cartagena', 'Real Cartagena FC')
teams.set ('Tigres FC Zipaquira', 'Tigres FC')
teams.set ('Barranquilla', 'Barranquilla FC')
teams.set ('Boyaca Chico', 'Boyaca Chico FC')
teams.set ('Real Santander', 'CD Real San Andres')
//Algerian Ligue 1
teams.set ('Chelghoum Laid', 'HB Chelghoum Laid')
teams.set ('MC Oran', 'MC Oran')
teams.set ('RC Arba', 'RC Arbaa')
teams.set ('MC Alger', 'MC Alger')
teams.set ('JS Saoura', 'JS Saoura')
teams.set ('WA Tlemcen', 'WA Tlemcen')
teams.set ('Kabylie', 'JS Kabylie')
teams.set ('ASO Chlef', 'ASO Chlef')
//Costa Rican Primera Division
teams.set ('Municipal Perez Zeledon', 'Municipal Perez Zeledon')
teams.set ('AD Guanacasteca', 'AD Guanacasteca')
teams.set ('Santos de Guapiles', 'AD Santos De Guapiles')
teams.set ('Deportivo Saprissa', 'Deportivo Saprissa')
teams.set ('CS Herediano', 'CS Herediano')
teams.set ('AD San Carlos', 'AD San Carlos')
teams.set ('CS Cartagines', 'CS Cartagines')
teams.set ('LD Alajuelense', 'Alajuelense')
teams.set ('Municipal Grecia', 'AD Municipal Grecia')
teams.set ('Guadalupe F.C', 'Guadalupe FC')
teams.set ('ADR Jicaral', 'ADR Jicaral')
teams.set ('Sporting San Jose FC', 'Sporting San Jose')
//Salvadoran Primera Division
teams.set ('Jocoro', 'Jocoro FC')
teams.set ('Chalatenango', 'AD Chalatenango')
teams.set ('CD Aguila', 'CD Aguila')
teams.set ('CD Luis Angel Firpo', 'Angel Firpo')
teams.set ('Santa Tecla', 'Santa Tecla ')
teams.set ('CD Atletico Marte', 'CD Atletico Marte')

module.exports = teams